# Generated by Django 3.1.7 on 2021-03-10 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='app.courier'),
        ),
        migrations.AlterField(
            model_name='courier',
            name='earnings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='courier',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
