# Generated by Django 3.1.7 on 2021-03-11 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210310_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='rating',
        ),
        migrations.AddField(
            model_name='courier',
            name='assigned_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignation',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignations', to='app.courier'),
        ),
    ]
