# Generated by Django 3.1.7 on 2021-03-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210311_0911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_time'
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DurationField(default=None, null=True),
        ),
    ]
