# Generated by Django 3.1.7 on 2021-03-11 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210311_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courier',
            name='earnings',
        ),
    ]
